/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TableIdRouteImport } from './routes/$tableId'
import { Route as TableIdIndexRouteImport } from './routes/$tableId/index'
import { Route as TableIdCartRouteImport } from './routes/$tableId/cart'
import { Route as TableIdCouponsRouteImport } from './routes/$tableId/coupons'

const TableIdRoute = TableIdRouteImport.update({
  id: '/$tableId',
  path: '/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const TableIdIndexRoute = TableIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TableIdRoute,
} as any)
const TableIdCartRoute = TableIdCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => TableIdRoute,
} as any)
const TableIdCouponsRoute = TableIdCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => TableIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$tableId': typeof TableIdRouteWithChildren
  '/$tableId/cart': typeof TableIdCartRoute
  '/$tableId/coupons': typeof TableIdCouponsRoute
  '/$tableId/': typeof TableIdIndexRoute
}
export interface FileRoutesByTo {
  '/$tableId/cart': typeof TableIdCartRoute
  '/$tableId/coupons': typeof TableIdCouponsRoute
  '/$tableId': typeof TableIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$tableId': typeof TableIdRouteWithChildren
  '/$tableId/cart': typeof TableIdCartRoute
  '/$tableId/coupons': typeof TableIdCouponsRoute
  '/$tableId/': typeof TableIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$tableId' | '/$tableId/cart' | '/$tableId/coupons' | '/$tableId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/$tableId/cart' | '/$tableId/coupons' | '/$tableId'
  id:
    | '__root__'
    | '/$tableId'
    | '/$tableId/cart'
    | '/$tableId/coupons'
    | '/$tableId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TableIdRoute: typeof TableIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$tableId': {
      id: '/$tableId'
      path: '/$tableId'
      fullPath: '/$tableId'
      preLoaderRoute: typeof TableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tableId/': {
      id: '/$tableId/'
      path: '/'
      fullPath: '/$tableId/'
      preLoaderRoute: typeof TableIdIndexRouteImport
      parentRoute: typeof TableIdRoute
    }
    '/$tableId/cart': {
      id: '/$tableId/cart'
      path: '/cart'
      fullPath: '/$tableId/cart'
      preLoaderRoute: typeof TableIdCartRouteImport
      parentRoute: typeof TableIdRoute
    }
    '/$tableId/coupons': {
      id: '/$tableId/coupons'
      path: '/coupons'
      fullPath: '/$tableId/coupons'
      preLoaderRoute: typeof TableIdCouponsRouteImport
      parentRoute: typeof TableIdRoute
    }
  }
}

interface TableIdRouteChildren {
  TableIdCartRoute: typeof TableIdCartRoute
  TableIdCouponsRoute: typeof TableIdCouponsRoute
  TableIdIndexRoute: typeof TableIdIndexRoute
}

const TableIdRouteChildren: TableIdRouteChildren = {
  TableIdCartRoute: TableIdCartRoute,
  TableIdCouponsRoute: TableIdCouponsRoute,
  TableIdIndexRoute: TableIdIndexRoute,
}

const TableIdRouteWithChildren =
  TableIdRoute._addFileChildren(TableIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  TableIdRoute: TableIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
